### PR TITLE
Create EigenFaces.md

### PR DESCRIPTION
**Pull request by mugsiiit**
This PR builds upon the existing article on PCA. In cases where covariance matrix cannot be calculated due to memory restrictions and number of images is smaller than dimension of image, we use a trick called Eigen Faces.

---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @mugsiiit 

Thanks for opening this PR but it's not currently meeting the requirements to be merged.
Please read the [Article Style Guide](tps://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#article-style-guide) and update your PR as needed.

Once the necessary changes have been made I'll review it.

**Comment by mugsiiit** [comment]
Hey @Asjas thanks for pointing out.
I realised I didn't have a title according to article style guide, which I have added. Cant see what the other errors are however.

**Comment by Asjas** [comment]
Hey @mugsiiit 

Please read this section of the [Contributing Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#travis-ci-build). All articles file names must be called `index.md`. 

Please fix it and I will review the PR.

**Comment by Asjas** [comment]
Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :tada:

**Pull request merged**
