### PR TITLE
fix codeblock labels: pages/css

### PR DESCRIPTION
**Pull request by bdeshi**
/src/pages/css/* patched for #587 

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by smsrkr** [comment]
Just a note: I'm patching for both #8086 and #8074 . these will not be referenced in upcoming PRs.

**Comment by smsrkr** [comment]
@nsuchy @erictleung anyone interested in this?

**Comment by nsuchy** [comment]
@smsrkr Thank you for the continued support, if you keep submitting I'll review and merge for you. Please let me know once you're ready for me to review this PR.

**Comment by smsrkr** [comment]
I am thinking of patching articles in folder-based batches. Such as, this one only touches files under src/pages/css.

I can't find any more fixable files in this folder, so you can consider this PR ready for review, thanks. :slightly_smiling_face:

**Comment by smsrkr** [comment]
-- --
And another thing: wouldn't it be better if the [style guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md/#code-blocks) prominently pointed out that codeblocks should always be in fenced style and have a syntax label, generic ones like text where no proper labels are appropriate. Should I open a issue/PR for this?

**Comment by domwakeling** [comment]
Open a PR on the  style guide I would think?

**Comment by nsuchy** [comment]
@smsrkr Will you create an issue (reference this pull request) so we can discuss this?

**Comment by smsrkr** [comment]
ok. discussion moved. :)

**Comment by joshalling** [comment]
I'm closing this as it looks like this was merged in #8152. Let me know if I am incorrect in this assumption and I will reopen.

**Pull request closed without merging**
