### PR TITLE
added helpful links

### PR DESCRIPTION
**Pull request by Ipshu41**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by hkyq** [comment]
I don't believe this will get merged, from [here](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md):

> We won't accept a PR that only adds links to the "More Information:" section.

**Comment by Asjas** [comment]
Hi @Ipshu41 

Thank you for your PR but currently we do not merge PRs that only add to the More Information section.
You can refer to the [Contributing Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#closing) here to see why we close certain PRs.

**Comment by Asjas** [comment]
@Ipshu41 

You created 5 different pull requests that each only add 1 link to a guide page.
I don't feel that your pull requests were made in the spirit of Hacktoberfest. Please feel free to contribute by making substantial contributions. Just opening a PR to add a link isn't sufficient.

**Comment by Ipshu41** [comment]
Hi,
Thanks for the input. I would really appreciate it if you could point me
towards the projects that requires minor front-end changes. I don't believe
I am capable of more than that.
Thanks.

**Pull request closed without merging**
