### PR TITLE
Added Visuals,prediction procedure and real life applications

### PR DESCRIPTION
**Pull request by Yugandhartripathi**
Added some visuals to make it more engaging and info regarding how actual predictions are made and what are some real life applications of logistic regression.

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by Yugandhartripathi** [comment]
Why is it failing the netlify test?Can someone help me resolve this?

**Comment by Asjas** [comment]
@Yugandhartripathi 

We are aware of the Netlify tests failing. It's a known issue. It's also not required to pass for a PR to be accepted.

Please don't open and close multiple PRs. Please ask in the future to save time.

**Comment by Yugandhartripathi** [comment]
Thanks for clarifying that. Sorry for those PR's , I was trying out different changes like branch name check status based on netlify failed log which said something about failed regex match to pass the test.

**Comment by QuincyLarson** [comment]
@Yugandhartripathi Awesome! Thanks! Congrats on your first open source contribution to this repository!

**Pull request merged**
