### PR TITLE
Added Template Literals to ES6

### PR DESCRIPTION
**Pull request by rachnaban**
Added Template Literals to ES6 Topic under JavaScript.

---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by rachnaban** [comment]
Added the title. Please verify.

**Comment by ezioda004** [comment]
There's already an article for template literals in `pages/javascript/template-literals`. Perhaps you could enhance that? There's no point in having 2 articles on the same topic.

**Comment by rachnaban** [comment]
> There's already an article for template literals in `pages/javascript/template-literals`. Perhaps you could enhance that? There's no point in having 2 articles on the same topic.

Is it possible to move that page under ES6 so that ES6 material is all together.

**Comment by ezioda004** [comment]
@rachnaban I've opened this #9608 since there's already ES6 articles which are not in that folder so instead of moving those into ES6 folder we could just move all the ES6 articles out of the folders which IMO is a better alternative.

**Comment by QuincyLarson** [comment]
@ezioda004 We're planning on leaving the ES6 folder where it is. I closed the issue related to this and explained my reasoning there. https://github.com/freeCodeCamp/guide/issues/9608

@rachnaban Thanks for writing this in-depth explanation.

**Pull request merged**
