### PR TITLE
Use proper em dashes in README

### PR DESCRIPTION
**Pull request by thomaskuntzz**
The proper dashes to use are em dashes when the goal is to indicate a break in the sentence

https://en.wikipedia.org/wiki/Dash

### CODE REVIEW

**Comment by thomaskuntzz** [comment]
@pertrai1 That's the typographically correct way to use em dashes in this case. I just checked and in fact both en dashes with spaces and em dashes without spaces can be used.

**Comment by thomaskuntzz** [comment]
The most important thing is consistency, so if en dashed with spaces are used everywhere this PR might not be relevant

**Comment by erictleung** [comment]
I was worried that they would render incorrectly or confusingly, but they turned out fine.

image

**Comment by amandeepmittal** [comment]
@thomaskuntzz Thanks for your contribution 👍.

**Pull request merged**
