### PR TITLE
Add enums guide

### PR DESCRIPTION
**Pull request by petarblazevski**

### CODE REVIEW

**Comment by jp-sauve** [comment]
This PR is being closed. While the source material allows copying without permission, plagiarized, copy-pasted, and unattributed work is not to be posted to this repository. 
This is your only warning. A repeated offence will earn you a ban from the repository.
https://basarat.gitbooks.io/typescript/docs/enums.html

Please read these pages before your next pull request
https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md and
https://www.freecodecamp.org/academic-honesty

**Comment by petarblazevski** [comment]
@jp-sauve I totally agree with you. I had a discussion on #3887 as well. I will update all of the content. The reason behind all of this is because I do visit the site quite often. As a developer, having the guides in one place is very important. That's why I took the liberty of taking some of the content from other sites and add it to this site.

**Comment by jp-sauve** [comment]
Sounds good! I like the version that you submitted, so with those changes we'd be happy to accept it.

**Comment by petarblazevski** [comment]
Thanks a lot

**Comment by domwakeling** [comment]
Marked as stale and closed due to inactivity. :disappointed:

Please make appropriate changes if you have the time :+1:

**Pull request closed without merging**
