### PR TITLE
Changed the article in such a way beginner can follow such as adding installing dependencies and also about installing create-react-app and also explained the code

### PR DESCRIPTION
**Pull request by highskillzz**
The previous article did not mention the initial setup like installing dependencies and how to place files. So I have modified it to such that it involves everything including about create-react-app and explained the code more

### CODE REVIEW

**Comment by highskillzz** [comment]
Can anyone tell me why did the deploy fail?

**Comment by Asjas** [comment]
Yes. 

The Netlify deployment fails and is a known problem. It's not a requirement for a PR to be merged.

**Comment by highskillzz** [comment]
@Asjas Thank you for clarifying that.

**Comment by paulywill** [comment]
@highskillzz 

IT CROWD

**Pull request merged**
