### PR TITLE
Add C++ Files text script using fstream

### PR DESCRIPTION
**Pull request by yaderson**
File text creating using fstream
Thank you 😊

### CODE REVIEW

**Comment by Asjas** [comment]
Hi,

Thanks for this pull request (PR).

Unfortunately, we are marking this PR invalid for hacktoberfest. We believe it does not follow the recommended guidelines:

> ### Quality Standards
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
> 
> - PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> - PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> - PRs that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by Asjas** [comment]
Please read and follow the [Article Style Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#article-style-guide) on your next PR to see what format your article should follow. :+1:

**Comment by yaderson** [comment]
So, will you look for problems in the published and non-added codes?

**Comment by Asjas** [comment]
We are looking for articles that are easy for beginners to understand and that explains a topic. 

Your PR contained code on it with no explanation of what is happening or how the code is working. There was no topic to your article. Your article should also follow all the Article Style Guide rules (correct folder name, correct file name, title, markdown formatting`.

**Comment by yaderson** [comment]
ok, correct and send new mind the pr. Thank

**Pull request closed without merging**
