### PR TITLE
PHP: Added article Installation of PHP

### PR DESCRIPTION
**Pull request by Chandra0505**
This article consists of steps for the  installation of  PHP on a system successfully.

---

## ✅️ By submitting this PR, I have verified the following:

- [complete] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [complete] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [complete] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @Chandra0505 

Thanks for opening this PR. Can you please read the [Contributing Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#article-style-guide) and make sure your PR adheres to the requirements. The file name is incorrect.

Once you have made the necessary change I will review it.

**Comment by Asjas** [comment]
You updated the `title`. Which shouldn't be changed. You need to change the file name. It's invalid.

All pages must be called `index.md`. And each new article must be in a separate folder.

**Comment by Chandra0505** [comment]
I have renamed it. Please review it now.

Can you please suggest me how can I synchronize my forked freeCodeCamp  repo with the original one to all latest updates.

Thanks for help.

**Comment by Asjas** [comment]
> Can you please suggest me how can I synchronize my forked freeCodeCamp repo with the original one to all latest updates.

That is already explained in the [Contributing Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#cloning-locally).

**Comment by Asjas** [comment]
Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :tada:

**Comment by Chandra0505** [comment]
Thank you @ for helping me.

You are doing such wonderful work for community for helping others.

**Pull request merged**
