### PR TITLE
Fix for smart contracts file breaking the tests

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Created a smart-contracts directory, moved the markup file to the new directory, and renamed the file index.md. Tests now pass with these changes.

---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by honmanyau** [comment]
@scissorsneedfoodtoo Thank you very much for submitting a fix! I literally created a commit when this came through! Unfortunately someone seems to have merged another article that breaks the build. In any case, I have merged this since it does fix the problem! Thank you very much for your contribution!

**Comment by scissorsneedfoodtoo** [comment]
@honmanyau, sorry about that! Wasn't sure if anyone else was doing the same fix. Thank you for reviewing and merging this.

Did just notice a problem with a folder name, Features-of-Blockchain. Are you working on a fix for that?

**Comment by honmanyau** [comment]
@scissorsneedfoodtoo No need to be sorry! I think we were working on it at the same time—there was no way to know that since this repository is moving at a very fast pace at the moment and Issues are not being created for most PRs. :)

I have submitted a PR for the Features-of-Blockchain issue just a bit earlier (#10022)—it's actually a plagiarised article so I have completed removed it.

Thank you very much for your help again! :)

**Comment by scissorsneedfoodtoo** [comment]
Yeah, things are moving almost too fast haha. Good thing we have people like you to help us review and fix things as they break! Thanks for your help, too ^^

**Comment by honmanyau** [comment]
And to **you**, too! :)

**Pull request merged**
