### PR TITLE
Fix markdown error in PR template

### PR DESCRIPTION
**Pull request by divayprakash**
Correctly renders checkboxes which were earlier being rendered as a list with brackets

### CODE REVIEW

**Comment by danhmanh** [comment]
[x ]

**Comment by danhmanh** [comment]
I think its not neccessary because when you add space between 2 bracket like this `[ ]`, participant have to delete a space to make markdown enable. `[x ]` doesnt work.

**Comment by erictleung** [comment]
@danhmanh I think the intent in this PR is that you create the pull request, and you can just click on the checkboxes to change them when you view them. This is probably in bikeshedding territory and really up to educating contributors that there shouldn't be an extra space.

I'll wait for others opinions on the matter. Given my cursory look at PRs, I think adding this space may confuse more people as you point out.

**Comment by joshalling** [comment]
I'll merge this since the freeCodeCamp and curriculum templates have the space. This way we will be consistent across the repos. Thanks @divayprakash!

**Pull request merged**
