### PR TITLE
Create a stub (index.md) for Gatsby.js

### PR DESCRIPTION
**Pull request by rachelfranklin1**
I'd like to contribute by documenting my learnings of Gatsby.js as I work with this static site generator extensively in work and I am also building my portfolio site using it. 

If you think this would be helpful (as it's pretty damn popular at the mo), please approve this PR to allow myself and others get to work writing up a guide for Gatsby newbies. 

---

## ✅️ By submitting this PR, I have verified the following

- [ ] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [ ] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [ ] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by rachelfranklin1** [comment]
hey @jsjoeio thanks for the tip! I believe I have fixed this - the stub should have the correct file path. 😎

I'm unsure how to get the Netlify check to pass - the error looks unrelated to my PR. Maybe you'd know how?

**Comment by jsjoeio** [comment]
@rachelfranklin1 nice work! 👏 It looks good now. I added in the 'stub template' so people know they can edit it.

**Comment by jsjoeio** [comment]
Hooray! It has been successfully merged in. Thank you and congrats on your first PR @rachelfranklin1 ! 🎉 Looking forward to seeing Gatsby content in the guides repo 😎

**Comment by rachelfranklin1** [comment]
Yayyyy! Thanks @jsjoeio - can't wait to start writing!

**Pull request merged**
