### PR TITLE
Added short terms

### PR DESCRIPTION
**Pull request by shamserunnisa**
**Description**

### CODE REVIEW

**Comment by nathanhannig** [comment]
@Bouncey netlify failed, can I just merge request? Also since I had conflicts to resolve, I don't need to squash commits?

This is my first time and I want to be sure I do it right. :)

**Comment by joshalling** [comment]
@nathanhannig We typically shouldn't merge a PR if it is failing any checks. When netlify fails it often just needs to be ran again. I went ahead retried it and it passed this time so you can go ahead and squash and merge.

**Comment by nathanhannig** [comment]
thank you @joshalling. How were you able to re-run the failed check? Is this where you need to make a change to a file so a new commit triggers the re-run?

**Comment by nathanhannig** [comment]
thank you @shamserunnisa for your first contribution! 👌

**Comment by joshalling** [comment]
@nathanhannig you need permissions on the FCC netlify account to retry a build, but adding whitespace and committing will also kick off a new build. I have been doing that with these old PRs that predate netlify to make sure they are ok to be merged.

**Pull request merged**
