### PR TITLE
Set up D3.js

### PR DESCRIPTION
**Pull request by adityasingh69**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @adityasingh69 

Thanks for opening this PR. Can you rather move this addition to a separate guide page? One called `Configure and Setup D3` perhaps? This current `index.md` page is getting a bit long. You can create a new folder in the `D3` directory and move this into there.

Also please make sure you use [code blocks](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#code-blocks) for any HTML or JS code you are putting in the guide page. Not everything is [rendering correctly](https://github.com/freeCodeCamp/guide/blob/8770e75c03ba17cf5730b2264bd4459d5b507565/src/pages/d3/index.md). There is a lot missing because it's being interpreted instead of being outputted on the page.

**Comment by adityasingh69** [comment]
I'll make the necessary changes, thanks for your feedback

**Comment by adityasingh69** [comment]
I have made the changes if you could look into it

**Comment by Asjas** [comment]
Hi @adityasingh69 

Please read our [Contributing Guidelines](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#travis-ci-build). It explains how an article should be created and what it should be named. Files need to be called `index.md` and each file needs to be in it's own folder. It helps if you follow the guidelines set out for contributions.

Clicking on the Travis CI Failed [Details](https://travis-ci.org/freeCodeCamp/guide/builds/436298869?utm_source=github_status&utm_medium=notification) will take you to the Travis page that explains the error.

Also, please choose which PR you are going to be creating this article in. You are doing the same work on #9191 and #9240 it seems.

**Comment by Asjas** [comment]
Closing as this is a duplicate of #9240.

**Pull request closed without merging**
