### PR TITLE
Newton galiza patch 2

### PR DESCRIPTION
**Pull request by NewtonGaliza**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following:

- [ ] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [ ] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [ ] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @NewtonGaliza 

Why are you opening and closing pull requests?

**Comment by NewtonGaliza** [comment]
Hello, sorry about that, i want to make a PR, but i don´t have much
experience in PR, that´s the why.

I´m sorry again.

Em qua, 3 de out de 2018 às 17:06, A-J Roos <notifications@github.com>
escreveu:

**Comment by Asjas** [comment]
I'd love to be able to merge your changes but it looks like there is an error with the Travis CI build. ⚠️

Once you resolve these issues, I will be able to review your PR and merge it. 😊

---

> Feel free to reference the [Article Style Guide](https://github.com/freeCodeCamp/guides#article-title) for this repo on formatting an article correctly so your Travis CI build passes. ✅
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝
Unfortunately your PR is failing the Travis Build. Please refer to our [Style Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#article-style-guide) on how a article should look.

**Comment by Asjas** [comment]
Closing this PR as it doesn't meet any of the requirements of the Contributing Guidelines.

**Pull request closed without merging**
