### PR TITLE
Tools: updated the conversion tools and added some theory

### PR DESCRIPTION
**Pull request by LucaBozzetto**
This might also fit in CS or Math category considering I've also added some explanation of the positioning system.

**Description**

### CODE REVIEW

**Comment by LucaBozzetto** [comment]
Hey @luandy64,
Thank you for your suggestion, definitely needed an improvement!
I'm going to fix this during this weekend

**Comment by domwakeling** [comment]
Hey @LucaBozzetto, as @luandy64 suggests in #8196 this might sit better as a separate article - given you've gone into the maths behind the conversion, it might sit well as (say) `src/pages/mathematics/binary-decimal-hex-conversion/index/md` or similar?

**Comment by LucaBozzetto** [comment]
I should have moved the file, let me know if it is ok!

**Comment by domwakeling** [comment]
@LucaBozzetto I'm afraid this has generated a 'complex' merge conflict (one that can't be resolved in the GitHub web interface. I'm not sure what the issue is, would have expected this to be OK

**Comment by raisedadead** [comment]
Hi @LucaBozzetto! 

Thanks for taking the time to prepare this pull-request.
I have resolved the conflict and landed this via a cherry pick of the commit.
 
See https://github.com/freeCodeCamp/guide/commit/4c4605558f2408cbb5f986f5a281a50c14990a7f

I am closing the PR. Your changes and commit has made it into the master branch. 😄 

Happy contributing.

**Pull request closed without merging**
