### PR TITLE
Updated index.md

### PR DESCRIPTION
**Pull request by sidkasat**
Added a bit of code blocks and indentation.

### CODE REVIEW

**Comment by domwakeling** [comment]
Hey @sidkasat. I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Whilst you're looking at these, could you please change the title to be something a little more descriptive than 'Update index.md' 🤔

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

**Comment by johnkennedy9147** [comment]
resolved merge conflicts, code fenced code snippets and added headings

**Comment by johnkennedy9147** [comment]
@domwakeling thanks - your too quick, spotted my error and you'd fixed it before I did!

**Comment by johnkennedy9147** [comment]
@sidkasat thanks for your contribution

**Pull request merged**
