### PR TITLE
added simple info about php and databases

### PR DESCRIPTION
**Pull request by SouthCoastDev**

### CODE REVIEW

**Comment by domwakeling** [comment]
Hey @SouthCoastDev. I think this content probably belongs in `src/pages/php/working-with-databases/index.md` (which is a stub) ⚠️ 

If you can make the appropriate edits (possibly easier to close this PR, pull the updated repo and make changes in a new PR?) I will be able to review your PR and merge it. 😊

**Comment by SouthCoastDev** [comment]
Hi Dom, 
Happy to move it!  Not quite sure how to? 
Is the info still required or has there been more stuff added since?
Thanks

**Comment by domwakeling** [comment]
The simplest way would probably be to get a copy of your content, close the current PR, edit the stub (which is unchanged at present) and submit a new PR.

Alternatively, you can 'move' a file that you've edited. It's probably best to have a look for a guide, but 'short form': when you edit a file in the GitHub interface the file name is in an editable text box; you can move up the folder tree by enter `../` and back down again by enter `{name_of_folder}/`. If you do it this way you can keep the current PR open, but need to ensure you get the exact filepath/file name so that your content will replace the current stub.

**Comment by SouthCoastDev** [comment]
Ok think I've done it right this time! This was one of my first ever attempts to use Github so I'm not surprised it wasn't right :)

**Comment by domwakeling** [comment]
No problem, it's not the most intuitive process in the world!

**Comment by domwakeling** [comment]
Hey @SouthCoastDev Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
