### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by devdot4**
Added a note to let the user to make sure to delete the old code and modify it with the new one within the code editor.

### CODE REVIEW

**Comment by domwakeling** [comment]
Hey @devdot4. I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️ 

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

**Comment by devdot4** [comment]
Hey, I will fix the conflicts as soon as possible. Sorry for a late response!

**Comment by domwakeling** [comment]
Hey @devdot4 I'm marking this as stale, but it'll remain open for at least another fortnight if you're able to make the changes :writing_hand:

**Comment by amandeepmittal** [comment]
Hey @devdot4 please consider submitting changes as per the review.

**Comment by devdot4** [comment]
Hello, I don't know why I didn't see these notifications but I will fix it.

**Pull request closed without merging**
