### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by hiparthparth**
Improved some grammar making the description more readable

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by amandeepmittal** [comment]
@hiparthparth Thank you for your contribution 👍

**Comment by ezioda004** [comment]
Hey @amandeepmittal, this PR added a new directory in the `src` folder as `src/java`, is this intended?
Since, theres already one in `src/pages/java`.

**Comment by thecodingaviator** [comment]
@ezioda004 , this was not intended on my side, I’ve even created an issue and a PR to remove the files and the folder, can you do it please?

**Comment by thecodingaviator** [comment]
@ezioda004 This is the one- https://github.com/freeCodeCamp/guide/pull/8706/files , this is all I made, maybe you cando the rest please?

**Pull request merged**
