### PR TITLE
Added new Section for Code Editors

### PR DESCRIPTION
**Pull request by blakeathomas**

### CODE REVIEW

**Comment by domwakeling** [comment]
Hey @blakeathomas 

I think this is a great idea, but that it would sit better in the `src/tools` directory, with your structure probably replacing the current `source-code-editors` sub-content. 🤔 

Before I merge the request, could I please ask you to:
* change your routes to `src/tools/code-editors/{editor}`
* as a minimum add 'this is a stub' content to each page

If you're able to also copy across the content from the current `source-code-editors` page as well (and maybe add the list in your root `index.md`?) that'd be fantastic, but I can merge without (and propose as an issue).

Thanks for your contribution 👍

**Comment by blakeathomas** [comment]
It could be up to 2 weeks before I could do that, I'm trying to finish school for the year as of rn but I would love to do that! Also, Would it be easier if I opened up a new pr?

**Comment by domwakeling** [comment]
To get the content you may find it easier to close this PR and start a new one, but I don't think you'll have any conflict issues if you update what you have. If you do decide to close the current PR, changes you proposed **should** still be available to review?

**Comment by blakeathomas** [comment]
Ok I'll just use the current fork. I'm haven't worked with forks and PR's very much so I wasn't sure. But like I said it might be a while till I can finish it.

**Comment by raisedadead** [comment]
Hi @blakeathomas 

Thanks a lot for taking the time to prepare this pull request. If this is your first time contributing, I would highly recommend making the same changes (copy/paste) from this PR on a fresh branch of your fork and proceed from there.

These changes having been made on `master` branch of your fork will not be easy to get in once you have gone back and forth with reviews, or someone has updated the same article.

I am going ahead and closing this, but please re-open a fresh PR when you are ready.

Thanks a lot, and happy contributing.

**Pull request closed without merging**
