### PR TITLE
Create an entry for Limit the Item Size Using the minmax Function

### PR DESCRIPTION
**Pull request by skywardcode**
CSS-Grid: Add Limit the Item Size Using the minmax Function article

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by skywardcode** [comment]
This is my first ever PR. I tried my best to follow the guidelines and instructions for submission so I hope it goes well!

**Comment by tchaffee** [comment]
@skywardcode Thanks for your contribution. In the future it's best to create two separate PRs for unrelated changes. If we have to reverse the changes in one file for some reason and we reverse this PR it would undo the other changes as well. I'll go ahead and merge it this time. Thanks again for your contribution.

**Comment by skywardcode** [comment]
Thanks for the advice @tchaffee. At the time, I thought that I _was_ doing separate Pull Requests, since I did them at different times, but I noticed that they went together after I pushed the second PR to the freecodecamp/guide repo. I will have to figure out how to keep from doing that in the future. 😆

**Comment by tchaffee** [comment]
@skywardcode If you need any help with that, ask over at the gitter chat and you can probably find someone to there. For the most part though, just check what files you commit and what's changed in those files. I use `gitk` to see what has been changed and committed. There are other visual tools you can use that make it easy to see what has been committed to a branch before pushing and creating a PR. Thanks for your contribution!

**Pull request merged**
