### PR TITLE
Correction of alignment in code examples

### PR DESCRIPTION
**Pull request by Nik-Pavlov**
I would like to suggest some small corrections of alignment in code examples

---

## ✅️ By submitting this PR, I have verified the following:

- [ ] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [ ] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [ ] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by honmanyau** [comment]
@Nik-Pavlov Thank you very much for submitting a PR. However, I will be closing this PR and #10034 and marking them as invalid because you have been submitting this type of minor fixes, which increases the workload for all maintainers and is unfair to contributors who are putting a lot of efforts in. It also goes against the spirit of Hacktoberfest, too (see appended).

If you would like to get these fixes and those in #10034 accepted, please combine them, and any other minor fixes that you want to apply to other articles, as a single PR.

> ### Quality Standards
> In line with Hacktoberfest value `#2` (Quantity is fun, Quality is key), we have provided examples of the quality standards we encourage. This applies mainly to beginners.
> 
> - PRs that are automated e.g. scripted opening PRs to remove whitespace / optimize images.
> - PRs that are disruptive e.g. taking someone else's branch/commits and making a PR.
> - PRs that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your PR count for October.

Learn more at https://hacktoberfest.digitalocean.com/details

**Comment by Nik-Pavlov** [comment]
@honmanyau, I agree with you that my PR seems to be against the spirit of Hacktoberfest, but does that mean that it is now impossible to fix such minor issues?
You decline someone's work and someone's desire to make FreeCodeCamp Guide looks better just because it is not big enough.

**Comment by Asjas** [comment]
@Nik-Pavlov 

You can combine both PRs into a larger PR.

**Comment by honmanyau** [comment]
@Nik-Pavlov I don't benefit in any way by not accepting your PR and it absolutely doesn't make me feel good doing so. If it helps to explain my position, here are some of the alternatives that I could have taken:

* Accept your PRs as is—which we both agree that it would seem to be against the spirit of Hacktoberfest.
* Merge your PR while marking it as invalid—this doesn't seem to make sense because that way it would be the same as taking your contribution while not acknowledging it.
* Close your own PR and submit my own while marking them as invalid—that also doesn't make sense because I would have taken your chance to make a contribution.

I don't mean to discourage you from contributing at all—that's why I suggested the alternative of submitting a PR by combining them as @Asjas has also pointed out, which I think is a reasonable solution; I would have made the same suggestion even when it is not Hacktoberfest, too. I hope that explains things a bit better!

**Pull request closed without merging**
