### PR TITLE
Update solution.

### PR DESCRIPTION
**Pull request by krmzl**
I added a solution.

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @krmzl. Thanks for opening this PR.

Please add an explanation and hints to the page and not just the solution.

Please see [this page](https://github.com/AdrianSkar/guide/blob/84b57c3ea837118a20d58d776d55e2a9bcb59609/src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator/index.md) and [this page](https://github.com/freeCodeCamp/guide/blob/master/src/pages/certifications/javascript-algorithms-and-data-structures/regular-expressions/ignore-case-while-matching/index.md) on the structure to use for these guide pages. Once you have updated the PR I will review it.

**Comment by krmzl** [comment]
Hi @Asjas  actually i opened this PR to make a test on deploy/netlify check. I dont understand why it returns a fail.it has become more and more recently.

**Comment by krmzl** [comment]
@Asjas I have updated the PR.

**Comment by Asjas** [comment]
Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :tada:

**Pull request merged**
