### PR TITLE
Fix: Created a new directory and renamed file to fix Travis build.

### PR DESCRIPTION
**Pull request by honmanyau**
The file merged in #9912 is incorrectly named and breaks Travis CI builds. The following changes were made to address the problem:

1. A new sub-directory was created to house the OOP article.
2. The incorrectly named file was moved to the sub-directory and renamed to `index.md`.
3. The title of the stub in the root directory was renamed to "Design Patterns".

---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by honmanyau** [comment]
I haven't labelled this with an `invalid` tag in case the Issue gets glossed over. To the maintainer who reviews this: please tag it as `invalid` so that it doesn't get contributed to my Hacktoberfest count if it's accepted and merged.

**Comment by Asjas** [comment]
Hey @honmanyau 

Thanks for fixing the Travis Build. :smile:

**Comment by Asjas** [comment]
I'm not going to mark this as `invalid`. It's still a valid contribution :+1:

**Comment by honmanyau** [comment]
@Asjas Thank you very much for sorting it out! I made the earlier comment because it feels somewhat awkward as to be submitting a PR to a repository that I am helping to maintain. 😓 Anyhow! Have a nice day/evening!

**Pull request merged**
