### PR TITLE
Write article about Fractions in Maths

### PR DESCRIPTION
**Pull request by Nythiennzo**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by thomaskuntzz** [comment]
Hi @Nythiennzo, thanks for your contribution! 👌

In your article, you say that a fraction has a value between 0 and 1, which is true, but I think it would be good to mention the difference between a fraction and a fractional number. Would you feel like adding that? 😉

**Comment by Nythiennzo** [comment]
I'm doing it right now!

**Comment by Nythiennzo** [comment]
It's done.
Please check it @thomaskuntzz

**Comment by alinepegas** [comment]
Hi @Nythiennzo.
What do you think about mentioning a fraction is a representation of a rational number?
Take a look at wikipedia:
[Rational Number](https://en.wikipedia.org/wiki/Rational_number)

**Comment by luandy64** [comment]
Hey @Nythiennzo 

Maybe this is just me, but the sentence you wrote, "A fractional number represents part of a whole number, a value between 0 and 1.", makes it sound like you are defining a "whole number" to be "a value between 0 and 1". Can we change that?

**Comment by Nythiennzo** [comment]
Hi @alinepegas,

Thanks for the suggestion.  I got the understanding that a rational number is a number that can be expressed as the fraction p/q where:
- p and q are integers
- q is not 0
 However this does not mean that only rational numbers are fractions.

For example e/10 is not a rational number but would be considered a fraction

For this reason, I do not think mentioning rational numbers is necessary.

**Pull request merged**
