### PR TITLE
Created an article on cookies manipulation

### PR DESCRIPTION
**Pull request by ElHombreNuevo**

### CODE REVIEW

**Comment by meetzaveri** [comment]
@vddesai1998 good example of cookies and its usage

**Comment by vddesai1998** [comment]
Thanks @meetzaveri
This is my first article for FCC guide and it feels great to be appreciated.

**Comment by domwakeling** [comment]
Hey @vddesai1998.  I'd love to be able to merge your changes but it looks like you have some merge conflicts - there have already been some changes accepted for this article you're editing. ⚠️ 

If you can review the conflicts and resolve your changes against the current article,  I will be able to review your PR and merge it. 👍

**Comment by domwakeling** [comment]
Marked as stale and closed due to inactivity. :disappointed:

Please make appropriate changes if you have the time :+1:

**Pull request closed without merging**
