### PR TITLE
Fix: Removed Dozens of Errant Links 

### PR DESCRIPTION
**Pull request by fantome149**
There is probably a **bug** which inserts this [link](https://forum.freecodecamp.org/images/emoji/emoji_one/rocket.png?v=3) in probably every other solution of Javascript Challenges. 

**Summary:**
-> **Removed Errant Links from _Javascript Algorithms And Data Structures Certification_** 
->**Fixed Markdown Typos**
->**Added Relevant Links**

PS: I have only checked errant links for Javascript Certification Challenges. They might also be present in other Certifications Solution Page
Kindly look into this bug.

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Thanks a lot @fantome149 👍 😄.

**Comment by fantome149** [comment]
@amandeepmittal  is it a bug or just typo's?

**Comment by fantome149** [comment]
@amandeepmittal  Is it a bug or just typo's?

**Comment by amandeepmittal** [comment]
@fantome149 what do you mean by that?

**Comment by fantome149** [comment]
@amandeepmittal, In my opinion, someone can't make so many typing mistakes in almost all solution pages and that too most of the time the same link in getting added inside the solution. 
So I think _there might be some error_ due to which such thing is happening.

**Comment by amandeepmittal** [comment]
Will check it out 👍.

**Pull request merged**
