### PR TITLE
C:made few changes

### PR DESCRIPTION
**Pull request by dabhitapan**
Added few facts, syntax comparison, how to assign and declare value and a format specifier . 😊

---

## ✅️ By submitting this PR, I have verified the following

- [ ] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [ ] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [ ] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @dabhitapan 

Thank you for your PR. Can I inquire why you are opening and closing multiple PRs? Can you rather stick with 1 PR and update it as you add more content?

**Comment by dabhitapan** [comment]
Hi @Asjas my PRs are failing checks.!

**Comment by Asjas** [comment]
@dabhitapan We are aware of the Netlify builds that are failing. In the future please leave a comment asking if that is a known problem instead of spamming PRs.

Your PR can be merged if the Netlify builds fail.

**Comment by Asjas** [comment]
The only check that needs to pass are the Travis CI check. Which is passing.

**Comment by dabhitapan** [comment]
I was not aware about that thanks for the info.

**Comment by QuincyLarson** [comment]
@dabhitapan Awesome! Thanks! Congrats on your first open source contribution to this repository! We would welcome more additions on C!

**Comment by dabhitapan** [comment]
@QuincyLarson I would be happy to contribute, thanks for merging my pr.

**Pull request merged**
