### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Tanvi-Goyal**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/.github/CONTRIBUTING.md).
- [] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Please take a look at your PR again and make sure it up to date with the latest branch.

**Comment by nsuchy** [comment]
Hey @Tanvi-Goyal

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by nsuchy** [comment]
I've resolved the merge conflict for you and will merge once the checks pass.

**Comment by nsuchy** [comment]
Hey @Tanvi-Goyal First thanks for contributing to the freeCodeCamp Guide, unfortunely I've had to temporarily put your PR on hold and apply the blocked label while further QAing and figuring an issue with merge conflicts and the resolution. I'm working on a quick resolution for you and appreciate your patience.

@QuincyLarson After resolving merge conflicts whatever content he made was replaced with something by another contributor so this PR doesn't appear to have any content. Can you figure out what went wrong? Thanks in advance.

**Comment by QuincyLarson** [comment]
@nsuchy @Tanvi-Goyal I'll let you know once we've fixed these build issues. Thanks for your patience.

**Comment by amandeepmittal** [comment]
I do not think this PR adds any value to the content. @nsuchy I request you to close this one.

**Comment by nsuchy** [comment]
@amandeepmittal There initially recall some changes. They seem to of been amended out. I’m closing this per request.

@Tanvi-Goyal Please don’t hesitate to comment if you’d like us to reopen this request and work on further changes.

**Pull request closed without merging**
