### PR TITLE
C#: create anonymous types article in csharp section

### PR DESCRIPTION
**Pull request by m-karimi**
create directory and article for anonymous types in c#

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@m-karimi, thank you for taking the time to improve this section of the guide. However, a lot of this seems to be taken directly from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types. Plagiarism is not allowed in the guide, so you'll have to rewrite this. Please let us know when you're finished and someone will be happy to take another look at your PR.

**Comment by m-karimi** [comment]
> 
> 
> @m-karimi, thank you for taking the time to improve this section of the guide. However, a lot of this seems to be taken directly from [docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types). Plagiarism is not allowed in the guide, so you'll have to rewrite this. Please let us know when you're finished and someone will be happy to take another look at your PR.

@scissorsneedfoodtoo as I've mentioned in the other pull request: 

> I have mentioned the resource I've used in the article, so I think it would not be considered as plagiarism.
If we are looking for original content in Freecodecamp guides, I would be happy to rewrite the article.

looking forward to hearing back from you!

**Comment by scissorsneedfoodtoo** [comment]
@m-karimi, yes, that's true that you mentioned it. But we still can't allow an exact copy of the Microsoft docs into the guide. Direct quotes are fine if you list the source like you did, but they would still require apostrophes and cannot make up the bulk of your article. If you were to rework the sentences and examples that would be perfectly fine and someone would be happy to merge it!

That being said, it would be best to wait until later this week to rewrite this. There are many changes happening around here and this repo will soon be archived. All of the articles will soon be moved to the main repo at https://github.com/freeCodeCamp/freeCodeCamp. Once that's done, please feel free to open another PR there!

**Comment by m-karimi** [comment]
@scissorsneedfoodtoo Ok, I will rewrite the article after the repo movement later this week

**Comment by QuincyLarson** [comment]
Thank you for your patience.

We have archived this Guide repository and moved the guide into our main https://github.com/freecodecamp/freecodecamp repostory.

Since this Guide repository is now archived, I'm closing this pull request.

I encourage you to take a look at the repository and consider contributing to it this Hacktoberfest.

We now have a much larger team QA'ing these pull requests and we should be able to review your pull request much faster this time. Here's an article I wrote with details for how to do this: https://www.freecodecamp.org/n/FDoftlSup

Thank you again for contributing to open source.

**Pull request closed without merging**
