### PR TITLE
Ruby Arrays: Documentation for count and usage of blocks for count method added

### PR DESCRIPTION
**Pull request by 8parth**
**Description**

- Documentation for `count` method in ruby added
- Introduction to blocks added, explained how blocks are used with `count` method

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@8parth, thank you for your contribution. Lots of great info here! Unfortunately there are some conflicts due to another PR that was merged. Could you resolve those and update your PR so we can get it merged?

**Comment by 8parth** [comment]
Unfortunately I deleted old repo, and now I am unable to do resolve conflicts. Is there a way I can fix it?

**Comment by scissorsneedfoodtoo** [comment]
@8parth, I see. Sorry, I didn't notice that earlier. The only way to resolve the conflicts at this point is to submit another PR. It would be best to wait until later this week, though. There are many changes happening around here and this repo will soon be archived. All of the Guide articles will soon be moved to the main repo at https://github.com/freeCodeCamp/freeCodeCamp. Once that's done, please feel free to open another PR there!

**Comment by QuincyLarson** [comment]
Thank you for your patience.

We have archived this Guide repository and moved the guide into our main https://github.com/freecodecamp/freecodecamp repostory.

Since this Guide repository is now archived, I'm closing this pull request.

I encourage you to take a look at the repository and consider contributing to it this Hacktoberfest.

We now have a much larger team QA'ing these pull requests and we should be able to review your pull request much faster this time. Here's an article I wrote with details for how to do this: https://www.freecodecamp.org/n/FDoftlSup

Thank you again for contributing to open source.

**Pull request closed without merging**
