### PR TITLE
fix/replace space with hyphen in folder names

### PR DESCRIPTION
**Pull request by jp-sauve**
**Description**

### CODE REVIEW

**Comment by domwakeling** [comment]
Hey @jp-sauve. I'd love to be able to merge your changes but it looks like you have some merge conflicts that can't be resolved in the GitHub web interface. ⚠️ 

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

**Comment by jp-sauve** [comment]
@domwakeling I've used the commandline instructions to resolve the file name conflicts, and pushed back the changes. I don't see anything updated here, but I'll ask in gitter and see if I've missed anything.

**Comment by jp-sauve** [comment]
I've followed the instructions for commandline resolution of this conflict, but I'm not sure what else to do! I don't see any conflicts locally, and the changes were pushed without error. I'm in gitter if you have any questions.

**Comment by domwakeling** [comment]
Hey @jp-sauve. If you've updated your local repo to match the upstream master (rebase?), then all I can think is close this PR and open up two fresh ones (one for each file) and see whether they solves it  ❓

**Comment by joshalling** [comment]
@jp-sauve I'm closing this stale PR. If you still want to contribute with these stubs, please do as @domwakeling suggests and open two new PRs.

**Pull request closed without merging**
