### PR TITLE
if-then-else

### PR DESCRIPTION
**Pull request by cwesta**
**Description**

### CODE REVIEW

**Comment by jp-sauve** [comment]
The failure is due to an error that existed when you forked. You need to rebase on upstream to get the fixes, and CI should work.

**Comment by cwesta** [comment]
can you explain in more detail? I'm a total new to this. I have read the guides and not sure what you mean exactly. Is it because when I forked the master branch I changed the name of my branches?

**Comment by jp-sauve** [comment]
No, it's because there was a bug when you forked. It has since been fixed, but you can't submit until your branch contains the fixes to at least allow travis to run.

**Comment by cwesta** [comment]
ok so how do I do that? or where could I learn to do that?

**Comment by 1andee** [comment]
Hey @cwesta,

I suspect your PR is failing the Travis build for the following reasons:
- The file `src/pages/vba/if-then-else` needs to be inside a new directory
- The file `src/pages/vba/if-then-else` should be named `index.md`

With changes applied, the path should look like this: `src/pages/vba/if-then-else/index.md`

As per JP, you'll also want to sync your fork using the following steps:

1. [Configuring a remote for a fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
2. [Syncing a fork](https://help.github.com/articles/syncing-a-fork/)

**Comment by domwakeling** [comment]
Closed as “stale” with no activity

**Pull request closed without merging**
