### PR TITLE
Created the example Hello World for Swift

### PR DESCRIPTION
**Pull request by OwboxAl3x**
Created the example Hello World for Swift

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by OwboxAl3x** [comment]
How do I fix that?

**Comment by Asjas** [comment]
@OwboxAl3x 

What do you want to fix? Your question is pretty vague.

**Comment by OwboxAl3x** [comment]
That why has my pull request been rejected?

**Comment by Asjas** [comment]
Hey @OwboxAl3x 

Thank you for your pull request but I don't feel that this is a substantial contribution. 
You haven't actually added any content so I will be closing this PR and marking it as `invalid`. 😓️

Feel free to open another PR though! 👍

**Comment by Asjas** [comment]
@OwboxAl3x Please add a substantial contribution in your PR. Changing the version number isn't substantial.

**Pull request closed without merging**
