### PR TITLE
Add content for Threads

### PR DESCRIPTION
**Pull request by scarescrow**

### CODE REVIEW

**Comment by tchaffee** [comment]
@scarescrow Thank you for your contribution. Someone has updated the article in another PR so this has merge conflicts now. Could you resolve the merge conflicts please so we can merge your contribution? Thanks!

**Comment by scarescrow** [comment]
Hi @tchaffee ,
I've merged them to the best of my logical ability. 
Hope the language is consistent.

**Comment by scarescrow** [comment]
I'm not sure why the checks are failing though.

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM! Thank you for your contribution, @scarescrow, and so sorry for the long delay in reviewing your PR. No need to worry about the failing checks -- another PR with a misnamed file broke them awhile back and we've just been ignoring them. It was just fixed recently, so future PRs should be fine.

Anyway, looking forward to your next contribution :+1: :+1:

**Pull request merged**
