### PR TITLE
Added hints: JavaScript ES6

### PR DESCRIPTION
**Pull request by HKumar99**
Created hints for JavaScript certification

---

## ✅️ By submitting this PR, I have verified the following

- [X] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [X] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [X] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by HKumar99** [comment]
Hello! For the past few weeks, my pull requests have had commits that have already been merged. I am not sure why this is the case...maybe because one of my commits (287d424) is still waiting for the Netlify test to pass (it's been like that for two weeks!). Could anyone guide me as to why this is the case?

**Comment by jsjoeio** [comment]
@HKumar99 First, thank you for all your hard work! 👍 

This could be that other pull requests with commits related to the same stubs/hints have been merged before yours? 

The Netlify builds were failing because of a previous error but it has been working fine now (as you can see in this PR). 

It may be better to do one hint/stub per pull request. That way, as a reviewer, we can look it over more quickly and approve it faster. That would be my advice!

**Comment by jsjoeio** [comment]
@HKumar99 I'm going to try my best to review these as soon as I can but since most of us do this our free time, it may not be until this weekend!

**Comment by jsjoeio** [comment]
Everything looks good to me! Thank you for all this work @HKumar99 ! The community is going to benefit from these A LOT. 😄  Once it passes the checks, I'll merge it!

**Pull request merged**
