### PR TITLE
Add Vagrant description

### PR DESCRIPTION
**Pull request by achillesp**
Added basic Vagrant description.

### CODE REVIEW

**Comment by rpalaciosg** [comment]
Hello, can I write a small example tutorial, how to create a development environment for java with Vagrant?

**Comment by amandeepmittal** [comment]
@achillesp can you please see those conflicts and resolve them? Let me know if you need any help. 

@rpalaciosg Yes you can!

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks everyone, I have resolved the conflicts and merged this. Please feel free to make a fresh PR to improve the article, should I have missed any thing.

Happy Contributing!

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks everyone, I have resolved the conflicts and merged this. Please feel free to make a fresh PR to improve the article, should I have missed any thing.

Happy Contributing!

**Pull request merged**
