### PR TITLE
Go: Replacing stub page for Go Structs with content

### PR DESCRIPTION
**Pull request by itmecho**
Updating stub page for go structs to have content

---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by itmecho** [comment]
Thanks @honmanyau! I'm curious how the CI passed the first time but then not with your commit? It seems to have failed on a completely unrelated file!

**Comment by honmanyau** [comment]
@itmecho Apologies for not having commented on editing I made yet! I got distracted for exactly the question you have asked! 😓 It appears that a file with an incorrect name was merged between now and when you first submitted the PR! It shouldn't affect your PR though! :)

**Comment by itmecho** [comment]
@honmanyau No worries! That would make sense :grinning:  I thought I was going crazy for a minute!

**Comment by honmanyau** [comment]
@itmecho Thank you for your understanding and a sorry for the troubles caused again! I have just now merged the PR—so thank you very much again for your contribution and congratulations on your first PR here! 🎉

**Pull request merged**
