### PR TITLE
adding some helpful guides

### PR DESCRIPTION
**Pull request by gareth-d85**
I have added some links to some guides and youtube videos.
---

## ✅️ By submitting this PR, I have verified the following:

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by gareth-d85** [comment]
i am not sure why my old commits are part of my new pull request as i have already did a pull request for them and was accepted

**Comment by Nirajn2311** [comment]
@gareth-d85 are you doing the new commits in the same branch as the old commits.

**Comment by gareth-d85** [comment]
@Nirajn2311 so am i doing something wrong? still learning about git and github.

**Comment by Nirajn2311** [comment]
@gareth-d85 it depends on the answer to my question? If you are doing new commits in the same branch then even the older commits will appear.

**Comment by gareth-d85** [comment]
@nirajn2311 yes I am doing the new commits in the same brach as the old commits.

**Comment by gareth-d85** [comment]
@nirajn2311 so how do I fix this problem?

**Comment by scissorsneedfoodtoo** [comment]
@gareth-d85, no worries, it takes some time to get used to Git, GitHub, and contributing. I've still got a lot to learn myself! You just had a minor conflict here in the Bootstrap index file, so I took care of that and got your changes merged.

Like @Nirajn2311 mentioned, when working on a project like this you'll generally make each change in a new branch off of the master branch. When making a pull request, a good rule of thumb is to switch to the master branch with `git checkout master`, then run `git pull --rebase upstream master` to make sure you have the most up-to-date version. Then run `git checkout -b NEW-BRANCH-NAME` to create a new branch and switch to it. After that, go ahead and make your changes. All of these steps and more can be found in the [Contributor's Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md).

Anyway, hope that helps! Thank you for helping us improve this section of the guide. Looking forward to your next contribution! :+1: :+1:

**Pull request merged**
