### PR TITLE
add stubs for challenges missing a certificate article

### PR DESCRIPTION
**Pull request by iabrenne**
Created 1463 stubs for challenges that do not have a corresponding certificate article. This should close [16388](https://github.com/freeCodeCamp/freeCodeCamp/issues/16388).

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by iabrenne** [comment]
Hmm not sure why deploy/netlify failed...

**Comment by thomaskuntzz** [comment]
Yes, sometimes the build fails for no apparent reason... The issue is being discussed in #7925

**Comment by iabrenne** [comment]
Thank you, @thomaskuntzz . Glad to see that this build failure is (probably) not my fault :)

**Comment by QuincyLarson** [comment]
@iabrenne Thanks for your patience. I've reached out to the Netlify team to see whether there's anything we can do. This is an important PR, and we will merge it as soon as we can get the build to pass. https://twitter.com/ossia/status/967151832836575232

**Comment by nsuchy** [comment]
@QuincyLarson Can you update me once the build is reattempted and successful? I have a few huge PRs I'd like to go through and check everything on, the failed netlify builds worry me that some change I'm not seeing breaks the build.

**Comment by QuincyLarson** [comment]
@nsuchy OK - I'll let you know once we've fixed this.

**Comment by Bouncey** [comment]
@iabrenne Thank you for your time and patience. We are working to resolve the issues hold this PR up as fast as possible

**Comment by QuincyLarson** [comment]
@iabrenne Thanks for all your hard work on this, and your extreme patience. 

We ended up completely overhauling the guide, and @Bouncey created stubs for the challenges we had after we launched the updated curriculum. So I'm closing this pull request. Thanks again for all your help with this.

**Pull request closed without merging**
