### PR TITLE
Hello everyone

### PR DESCRIPTION
**Pull request by issea1484**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following:

- [ ] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md`, since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Additional PR title examples:
    - **Git: edit Git Commit article**
    - **PHP: create PHP section and add Data Structures article**
- [ ] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [ ] No plagiarized, duplicate, or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by ezioda004** [comment]
Hi @issea1484,
Can you explain the point of copying?

**Comment by Nightfirecat** [comment]
Seems to be a spam PR to buffer their Hacktoberfest PR count: https://hacktoberfest.digitalocean.com/stats/issea1484

I would recommend closing this and reporting it to Hacktoberfest (I'm not sure of the best way to do this though...)

**Comment by Asjas** [comment]
We just mark it as `invalid`.

@ezioda004 I would suggest closing it as well and marking it as `invalid`.

**Comment by ezioda004** [comment]
@Asjas Got it, thanks.

**Pull request closed without merging**
