### PR TITLE
Created Stub on Automating Task using Cron

### PR DESCRIPTION
**Pull request by neal0892**
Highlighted use of Linux in webservers and how automated tasks are run on 24*7 servers using crontab in linux .

### CODE REVIEW

**Comment by prahladannamraju** [comment]
Hi @neal0892 ,
Just ran into the same issue. Add this to the top of your index.md file (without extra spaces) to pass the build.

---
title: Article title here
---

**Comment by neal0892** [comment]
@prahladannamraju How can I create a subfolder within linux folder

**Comment by prahladannamraju** [comment]
@neal0892 navigate to the main [Linux folder](https://github.com/freeCodeCamp/guides/tree/master/src/pages/linux), click "Add new file", then type in "name-of-your-new-subfolder/" and another text box will pop up for your file name, which will be named "index.md".

**Comment by neal0892** [comment]
@prahladannamraju Thanks man .....That just fixed the issue and passed the check.

**Comment by prahladannamraju** [comment]
@neal0892  you got it!

**Comment by imcodingideas** [comment]
@neal0892 Thank you so much for your first time contribution to Free Code Camp! I've checked everything, and this looks good to pushed.

**Pull request merged**
