### PR TITLE
Replace stub with guide; JS If statements

### PR DESCRIPTION
**Pull request by AdrianSkar**
Replacing stub with a guide. I took my [previous one](https://github.com/freeCodeCamp/guide/pull/8367) as reference. 

---

## ✅️ By submitting this PR, I have verified the following

- [X] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [X] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [X] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by Asjas** [comment]
Hi @AdrianSkar 

Thank you for your PR but currently we do not merge PRs that only add to the More Information section.
You can to refer to the [Contributing Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#closing) here.

**Comment by AdrianSkar** [comment]
@Asjas That was only my last fix (don't know how to modify the first commit) but the first commit was an entire guide page, I can delete the links formatting one if you wish, please review it. 
Thank you.

**Comment by Asjas** [comment]
Hi @AdrianSkar. I see now that there were 2 commits. My apologies.

I have merged your PR. :+1:

**Comment by AdrianSkar** [comment]
Great! Thank you @Asjas!

**Pull request merged**
